### ISSUE TITLE
Overriding Your Routes

### ISSUE THREAD

**Issue by changefox** [pvtl/voyager-pages#4]
Hi I'd like to use my own controller for showing the pages created. 

I did try
`Route::get('/{slug}', ['uses' => 'PageController@show', 'as' => 'getPage']);`
as per the Laravel documentation but this still insists on the default routes from Voyager-Pages

**Comment by changefox** [comment]
😢

**Comment by Jean-PierreGassin** [comment]
Hey @changefox, from memory the routes loaded by this package will override your own definitions because of the priority in `app.php` OR because the package is being automatically included using Laravel's automatic Service Provider loader.

If you manually place the package above your application specific providers in `app.php` you should be able to override any existing routes.

Let me know how you go.

**Comment by changefox** [comment]
Got it working, not sure if I've broken something else yet but all seems to be ok

In 5.5 you can exclude auto loading of the service provider in composer.json

```
    "extra": {
        "laravel": {
            "providers": [
                "Pvtl\\VoyagerPages\\Providers\\PagesServiceProvider"
            ]
        }
    },
```

Thanks @Jean-PierreGassin for pointing me in the right direction :)

**Comment by Jean-PierreGassin** [comment]
No worries @changefox. glad you got there in the end.
